version: '3.1'

services:

  mysql:
      image: 'mysql:5.7'
      command: --max_allowed_packet=32505856
      working_dir: /application
      volumes:
          - '.:/application'
          - .:/docker-entrypoint-initdb.d
      environment:
          - MYSQL_ROOT_PASSWORD=283976
          - MYSQL_DATABASE=clase20
          - MYSQL_USER=root
          - MYSQL_PASSWORD=2283976
      ports:
          - '33002:3306'

volumes:
  db_data: